# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Gradient Network
email: site@gradient.network
description: > # this means to ignore newlines until "baseurl:"
    Algorithmic trading with machine learning.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://gradient.network" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
